"""読んだ結果を TEI/XML にする。

形は [tei-scanner](https://github.com/nakamura196/tei-scanner) と揃える。
1 ページ = 1 `<surface>` + `<graphic>`、1 行 = 1 `<zone>` と `<lb corresp="#…">`。
同じ形にしておくと、TEI/IIIF エディタがそのまま開ける。

**枠を返さないエンジン(PaddleOCR-VL の版面読み)では `<zone>` を出さない。**
面積の無い枠を並べると、エディタ側で行が選べなくなる。

**木(ElementTree)を組んでから書き出さない。** 行の文字は `<lb/>` の直後に
続けて置く形なので、書き出し側に空白の入れ方を任せると並びが崩れる。
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass, field
from datetime import date
from typing import TYPE_CHECKING

if TYPE_CHECKING:  # 実体は engines 側。書き出しのためだけに取り込まない。
    from ..engines import Line

# XML に入れてよくない制御文字。OCR の結果に紛れると、書けても開けない XML になる。
_FORBIDDEN = {c for c in range(0x20) if c not in (0x09, 0x0A, 0x0D)} | {0x7F}


@dataclass
class Page:
    """書き出す 1 ページ。`lines` の枠は元画像の画素座標で (x, y, w, h)。"""

    lines: Sequence[Line]
    width: int
    height: int
    # <graphic url="…">。TEI を置く場所から見た相対の道を入れる。
    image_url: str = ""


@dataclass
class Meta:
    title: str = "Untitled"
    # 読んだ道具の名前。responsibility statement に入れる。
    engine: str = ""
    # どこから読んだか(ファイル名など)。分かるときだけ入れる。
    source: str = ""
    language: str = "ja"
    date: str = field(default_factory=lambda: date.today().isoformat())


def build(pages: Sequence[Page], meta: Meta) -> str:
    out: list[str] = ['<?xml version="1.0" encoding="UTF-8"?>']
    out.append(f'<TEI xmlns="http://www.tei-c.org/ns/1.0" xml:lang="{_attr(meta.language)}">')
    out += _header(meta)
    out += _facsimile(pages)
    out += _body(pages)
    out.append("</TEI>")
    return "\n".join(out) + "\n"


# --- 見出し ---------------------------------------------------------------


def _header(meta: Meta) -> list[str]:
    out = [
        "  <teiHeader>",
        "    <fileDesc>",
        "      <titleStmt>",
        f"        <title>{_text(meta.title)}</title>",
    ]
    if meta.engine:
        out += [
            "        <respStmt>",
            "          <resp>Automated transcription</resp>",
            f"          <name>{_text(meta.engine)}</name>",
            "        </respStmt>",
        ]
    out += [
        "      </titleStmt>",
        "      <publicationStmt>",
        "        <publisher>—</publisher>",
        f'        <date when="{_attr(meta.date)}"/>',
        "      </publicationStmt>",
        "      <sourceDesc>",
        "        <p>Generated by Local OCR from OCR of scanned page images.</p>",
    ]
    if meta.source:
        out.append(f"        <p>Source: {_text(meta.source)}</p>")
    out += ["      </sourceDesc>", "    </fileDesc>", "  </teiHeader>"]
    return out


# --- 版面 -----------------------------------------------------------------


def _facsimile(pages: Sequence[Page]) -> list[str]:
    out = ["  <facsimile>"]
    for i, page in enumerate(pages):
        w, h = max(0, int(page.width)), max(0, int(page.height))
        out.append(f'    <surface xml:id="{_surface_id(i)}" ulx="0" uly="0" lrx="{w}" lry="{h}">')
        if page.image_url:
            out.append(
                f'      <graphic url="{_attr(page.image_url)}" width="{w}px" height="{h}px"/>'
            )
        for j, line in enumerate(page.lines):
            if not line.box:
                continue
            ulx, uly, lrx, lry = _corners(line.box, w, h)
            out.append(
                f'      <zone xml:id="{_zone_id(i, j)}" '
                f'ulx="{ulx}" uly="{uly}" lrx="{lrx}" lry="{lry}"/>'
            )
        out.append("    </surface>")
    out.append("  </facsimile>")
    return out


def _corners(box: tuple[int, int, int, int], width: int, height: int) -> tuple[int, int, int, int]:
    """(x, y, w, h) を四隅に直す。版面からはみ出した分は端で止める。

    Apple Vision の枠は 0..1 の割合から画素に直しているので、丸めで 1px はみ出る。
    はみ出たままだと、エディタが版面の外に枠を描く。
    """
    x, y, w, h = (round(v) for v in box)
    ulx = min(max(x, 0), width)
    uly = min(max(y, 0), height)
    lrx = min(max(x + w, ulx), width)
    lry = min(max(y + h, uly), height)
    return ulx, uly, lrx, lry


# --- 本文 -----------------------------------------------------------------


def _body(pages: Sequence[Page]) -> list[str]:
    out = ["  <text>", "    <body>", "      <p>"]
    for i, page in enumerate(pages):
        out.append(f'        <pb n="{i + 1}" facs="#{_surface_id(i)}"/>')
        for j, line in enumerate(page.lines):
            # 枠のある行だけ zone を指す。無い行は corresp を書かない。
            corresp = f' corresp="#{_zone_id(i, j)}"' if line.box else ""
            out.append(f'        <lb{corresp} n="{j + 1}" type="line"/>{_text(line.text)}')
    out += ["      </p>", "    </body>", "  </text>"]
    return out


# --- 細かいところ ---------------------------------------------------------


def _surface_id(index: int) -> str:
    return f"f{index + 1}"


def _zone_id(page_index: int, line_index: int) -> str:
    return f"f{page_index + 1}_l{line_index + 1}"


def _clean(s: str) -> str:
    return "".join(c for c in s if ord(c) not in _FORBIDDEN)


def _text(s: str) -> str:
    return _clean(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _attr(s: str) -> str:
    return _text(s).replace('"', "&quot;").replace("'", "&apos;")
